//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAspProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_info()
        {
            this.customerConsulting_info = new HashSet<customerConsulting_info>();
        }
    
        public int idCustomer { get; set; }
        public string nameCustomer { get; set; }
        public Nullable<System.DateTime> birthCustomer { get; set; }
        public string sexCustomer { get; set; }
        public string phoneNumberCustomer { get; set; }
        public string emailCustomer { get; set; }
        public string addressCustomer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerConsulting_info> customerConsulting_info { get; set; }
    }
}
