//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAspProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerConsulting_info
    {
        public int idCustomer { get; set; }
        public int idStaff { get; set; }
        public int idProduct { get; set; }
        public string textInfo { get; set; }
    
        public virtual Customer_info Customer_info { get; set; }
        public virtual Product Product { get; set; }
        public virtual Staff_info Staff_info { get; set; }
    }
}
