//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAspProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff_info()
        {
            this.Accounts = new HashSet<Account>();
            this.customerConsulting_info = new HashSet<customerConsulting_info>();
        }
    
        public int idStaff { get; set; }
        public string nameStaff { get; set; }
        public Nullable<System.DateTime> birthStaff { get; set; }
        public string sexStaff { get; set; }
        public string phoneNumberStaff { get; set; }
        public string emailStaff { get; set; }
        public string addressStaff { get; set; }
        public string positionStaff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerConsulting_info> customerConsulting_info { get; set; }
    }
}
